#4 Issue
pklgn/recursive-descent pull request #5
Opened 2023-01-03 13:26 UTC by beta442

#4

- Перенастроил проект под CMake
- Поправил структуру тестов и сами тесты
- Поправил структуру проекта

2023-01-03 13:27 UTC, beta442 commented
ну, теперь дышаться будет посвободнее

2023-01-03 14:29 UTC, lich906 requested changes

2023-01-03 14:29 UTC, lich906 commented on src/parser/Parser.h
> +	using InputStreamR = std::istream&;
выглядит как using-и ради using-ов, почему просто не писать `std::istream&` ?

2023-01-03 14:29 UTC, lich906 commented on src/parser/context/ParserContext.h
> +namespace parser::context
для чего нам эта куча разных неймспейсов? вроде у нас не так много всего, чтобы названия начинали конфликтовать, да и код для использования в виде библиотеки как-то не тянет

2023-01-03 14:29 UTC, lich906 commented on src/parser/lexer/Lexer.h
> -		std::string actualValue;
тут дефолтный конструктор и так вызывается

2023-01-03 14:29 UTC, lich906 commented on tests/pch.h
> +namespace test
опять же -- неймспейс излишний

2023-01-03 15:16 UTC, beta442 commented on src/parser/Parser.h
> +	using InputStreamR = std::istream&;
мне лень набирать `std`, да потом ещё `istream`, ждать suggestion

фу!

2023-01-03 15:17 UTC, beta442 commented on src/parser/lexer/Lexer.h
> -		std::string actualValue;
у меня ide подсвечивала, решил добавить

2023-01-03 16:03 UTC, lich906 commented on src/parser/Parser.h
> +	using InputStreamR = std::istream&;
зато теперь чтобы разобраться в сигнатуре функции, нужно заглядывать сюда, чтобы понять что это обычный std::istream&

2023-01-09 09:50 UTC, pklgn commented
LGTM!

2023-01-09 09:50 UTC, merged